settings:
  # Available variables:
  # {mob_damage} - mob default damage
  # {mob_health} - mob default health
  # {level} - mob level
  # ANY PLAYER-UNRELATED PLACEHOLDERAPI PLACEHOLDER
  damage-formula: "{mob_damage}+({mob_damage}*{level}/100)"
  health-formula: "{mob_health}*(1+{level}/100)"
  check-radius: 10 #A radius to check for players to calculate level
  display-by-range: true #Display custom mob names by range instead of only when hovering over them.
  display-range: 5 #Range to display custom mob names (Only if display-by-range is true)
  enable-mob-names: true #Wether plugin should add custom formatted names to mobs that it spawn
  name-format: "&6Lvl {lvl}&8. | &f{mob} &8| &c&l❤ &f{health}&8/&f{maxhealth}" #Custom mob name format
  health-format-max-places: 2
  # Available variables:
  # {sumall} - summ player level from all skills
  # {skillcount} - skills count
  # {agility} - player agility level
  # {alchemy} - player alchemy level
  # {archery} - player archery level
  # {defence} - player defence level
  # {enchanting} - player enchanting level
  # {endurance} - player endurance level
  # {excavation} - player excavation level
  # {farming} - player farming level
  # {fighting} - player fighting level
  # {fishing} - player fishing level
  # {foraging} - player foraging level
  # {forging} - player forging level
  # {healing} - player healing level
  # {mining} - player mining level
  # {sorcery} - player sorcery level
  # {sumlevel_global} - summ level of all players online
  # ANY PLACEHOLDERAPI PLACEHOLDER
  player-level-formula: "{sumall}" #ALL FORMULAS SUPPORT PLACEHOLDERAPI PLACEHOLDERS!
  # Available variables:
  # {sumlevel} - summ level of all players in the check-radius
  # {playercount} - count of players in check-radius
  # {highestlvl} - highest of player levels in check-radius
  # {lowestlvl} - highest of player levels in check-radius
  # {sumlevel_global} - summ level of all players online
  # {location_x} - X coordinate of the mob
  # {location_y} - Y coordinate of the mob
  # {location_z} - Z coordinate of the mob
  # ANY PLAYER-UNRELATED PLACEHOLDERAPI PLACEHOLDER
  mob-level-formula: "{sumlevel}/{playercount}" #ALL FORMULAS SUPPORT PLACEHOLDERAPI PLACEHOLDERS!
  # Available variables:
  # {distance} - distance from world spawnpoint
  # {sumlevel_global} - summ level of all players online
  # {location_x} - X coordinate of the mob
  # {location_y} - Y coordinate of the mob
  # {location_z} - Z coordinate of the mob
  # ANY PLAYER-UNRELATED PLACEHOLDERAPI PLACEHOLDER
  default-mob-level-formula: "{distance}*0.01"

mob-replacements: # Supports any minecraft monster
  type: whitelist # whitelist/blacklist
  list: # The list itself (use - "*" to enable/disable all mobs)
    - "*"
    - "ZOMBIE"

mobs:
  blaze: Ифрит
  cave_spider: Пещерный паук
  creeper: Крипер
  enderman: Эндермен
  endermite: Эндермит
  evoker: Пробудитель
  evoker_fangs: Шипы пробудителя
  ghast: Гаст
  giant: Гигант
  guardian: Страж
  husk: Кадавр
  illusioner: Иллюзионист
  piglin: Пинглин
  hoglin: Хоглин
  shulker: Шалкер
  silverfish: Чешуйница
  skeleton: Скелет
  slime: Слизнь
  spider: Паук
  vex: Вредина
  villager: Житель
  vindicator: Поборник
  witch: Ведьма
  wither_skeleton: Скелет-иссушитель
  zombie: Зомби
  drowned: Утопленник
  magma_cube: Магма куб
  piglin_brute: Брутальный пиглин
  pillager: Разбойник
  ravager: Разоритель
  zombified_piglin: Зомбифи-Пиглин
  zombie_villager: Зомби-Житель
  stray: Зимогор